# Generated by Django 5.0.6 on 2024-05-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_picture',
            field=models.ImageField(blank=True, default='deault_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
