# Generated by Django 5.0.6 on 2024-05-09 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_logo', models.ImageField(blank=True, default='media/default_images/user.png', null=True, upload_to='company_logos/')),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_created=True)),
                ('model', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('year_manufactured', models.IntegerField()),
                ('about', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, default='media/default_images/car.png', null=True, upload_to='product_images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.company')),
            ],
            options={
                'db_table': 'Cars',
            },
        ),
    ]
